server:
  port: 8090

# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# ChatGPT SDK Config
chatgpt:
  sdk:
    config:
      # 官网地址 https://api.openai.com/
      api-host: https://pro-share-aws-api.zcyai.com/
      # 官网申请 https://platform.openai.com/account/api-keys
      api-key: sk-lFAkwdXFIFI93gvF4183917b5b42491e864b538862118692
      # 自主申请 http://api.xfg.im:8080/authorize?username=xfg&password=123 - 有时效性，主要为了大家学习使用
      auth-token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4ZmciLCJleHAiOjE2ODM5NDU3NDcsImlhdCI6MTY4Mzk0MjE0NywianRpIjoiM2QyMDExMTYtNmVjMS00Y2UzLWJhYzgtYzYxYmVmN2ZmNWE5IiwidXNlcm5hbWUiOiJ4ZmcifQ.3FDvUNuNoGemKLhcgagy8WH7xHwRU37t--BuH0N9skg

# 微信公众号配置信息
# originalid：原始ID
# appid：个人AppID
# token：开通接口服务自定义设置
wx:
  config:
    originalid: gh_584b96734eb7
    appid: wxa37f5d28423fa832
    token: b8b6


# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml